name: Release

on:
  release:
    types: [published]

jobs:
  build-and-test:
    name: Build, pack and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: |
          nuget pack Moq.Contrib.ExpressionBuilders.Logging.nuspec -Version ${{ github.event.release.name }} -Symbols -SymbolPackageFormat snupkg

      - name: Push
        run: |
          nuget push Moq.Contrib.ExpressionBuilders.Logging*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}